name: PR on master is not allowed, All PR should target develop branch.
# action that simply fails on PRs that are based on master 
on: 
  pull_request:
    branches: 
      - master

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: failfast
        run: exit 1
